version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    ACCOUNT_ID: "801333664660"
    ImageName: "simple-docker-service-0ed19a32f335"  # <- igual ao repositório do ECR
    CONTAINER_PORT: "8080"                             # <- a porta que seu app usa

phases:
  pre_build:
    commands:
      - echo "Login no ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo "Build da imagem..."
      - docker build -t $ImageName -f ./Dockerfile .
  post_build:
    commands:
      - echo "Tag & push..."
      - docker tag $ImageName:latest $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ImageName:latest
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ImageName:latest

      - echo "Gerando Dockerrun.aws.json para o Elastic Beanstalk..."
      - |
        cat > Dockerrun.aws.json <<EOF
        {
          "AWSEBDockerrunVersion": "1",
          "Image": {
            "Name": "$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ImageName:latest",
            "Update": "true"
          },
          "Ports": [
            { "ContainerPort": "$CONTAINER_PORT" }
          ]
        }
        EOF

artifacts:
  files:
    - Dockerrun.aws.json