version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    ECR_REPO: 801333664660.dkr.ecr.us-east-1.amazonaws.com/simple-docker-service-0ed19a32f335
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo "Login no ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO
  build:
    commands:
      - echo "Build da imagem..."
      - docker build -t bia:latest -f ./Dockerfile .
      - docker tag bia:latest $ECR_REPO:$IMAGE_TAG
  post_build:
    commands:
      - echo "Push pro ECR..."
      - docker push $ECR_REPO:$IMAGE_TAG
      - echo "Gerando Dockerrun.aws.json..."
      - |
        cat > Dockerrun.aws.json << 'JSON'
        {
          "AWSEBDockerrunVersion": "1",
          "Image": {
            "Name": "801333664660.dkr.ecr.us-east-1.amazonaws.com/simple-docker-service-0ed19a32f335:latest",
            "Update": "true"
          },
          "Ports": [
            { "ContainerPort": "8080" }
          ]
        }
        JSON

artifacts:
  files:
    - Dockerrun.aws.json

