version: 0.2

phases:
  pre_build:
    commands:
      - echo Fazendo login no ECR...
      - AWS_DEFAULT_REGION=us-east-1
      - REPOSITORY_URI=801333664660.dkr.ecr.us-east-1.amazonaws.com/bia
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 801333664660.dkr.ecr.us-east-1.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build iniciado em `date`
      - echo Gerando imagem da BIA...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build finalizado com sucesso em `date`
      - echo Fazendo push da imagem para o ECR...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG

      # >>> A PARTE CRÍTICA PARA O BEANSTALK <<<
      - echo Gerando Dockerrun.aws.json para o Elastic Beanstalk...
      - |
        cat > Dockerrun.aws.json << 'JSON'
        {
          "AWSEBDockerrunVersion": "1",
          "Image": {
            "Name": "801333664660.dkr.ecr.us-east-1.amazonaws.com/bia:latest",
            "Update": "true"
          },
          "Ports": [
            { "ContainerPort": "3000" }
          ]
        }
        JSON
artifacts:
  files:
    - Dockerrun.aws.json
